spring:
  application:
    name: okchat
  docker:
    compose:
      enabled: false
  output:
      enabled: ALWAYS # Enable colored output
  
internal:
  services:
    user:
      url: http://localhost:8080
    ai:
      url: http://localhost:8080
