apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-scripts
  namespace: okchat
  labels:
    app: okchat-mysql
    component: database
data:
  00_init.sql: |
    -- Create database if not exists
    CREATE DATABASE IF NOT EXISTS okchat
        CHARACTER SET utf8mb4
        COLLATE utf8mb4_unicode_ci;
    
    -- Use the database
    USE okchat;
    
    -- Grant all privileges to root user
    GRANT ALL PRIVILEGES ON okchat.* TO 'root'@'%';
    FLUSH PRIVILEGES;
    
    -- Create tables for Spring Cloud Task
    CREATE TABLE IF NOT EXISTS TASK_EXECUTION (
        TASK_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
        START_TIME DATETIME DEFAULT NULL,
        END_TIME DATETIME DEFAULT NULL,
        TASK_NAME VARCHAR(100),
        EXIT_CODE INTEGER,
        EXIT_MESSAGE VARCHAR(2500),
        ERROR_MESSAGE VARCHAR(2500),
        LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        EXTERNAL_EXECUTION_ID VARCHAR(255),
        PARENT_EXECUTION_ID BIGINT
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
    
    CREATE TABLE IF NOT EXISTS TASK_EXECUTION_PARAMS (
        TASK_EXECUTION_ID BIGINT NOT NULL,
        TASK_PARAM VARCHAR(2500),
        CONSTRAINT TASK_EXEC_PARAMS_FK FOREIGN KEY (TASK_EXECUTION_ID)
            REFERENCES TASK_EXECUTION(TASK_EXECUTION_ID)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
    
    CREATE TABLE IF NOT EXISTS TASK_TASK_BATCH (
        TASK_EXECUTION_ID BIGINT NOT NULL,
        JOB_EXECUTION_ID BIGINT NOT NULL,
        CONSTRAINT TASK_EXEC_BATCH_FK FOREIGN KEY (TASK_EXECUTION_ID)
            REFERENCES TASK_EXECUTION(TASK_EXECUTION_ID)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
    
    CREATE TABLE IF NOT EXISTS TASK_SEQ (
        ID BIGINT NOT NULL,
        UNIQUE_KEY CHAR(1) NOT NULL,
        CONSTRAINT UNIQUE_KEY_UN UNIQUE (UNIQUE_KEY)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
    
    INSERT INTO TASK_SEQ (ID, UNIQUE_KEY) 
    SELECT * FROM (SELECT 0 AS ID, '0' AS UNIQUE_KEY) AS tmp
    WHERE NOT EXISTS (SELECT * FROM TASK_SEQ);
    
    CREATE TABLE IF NOT EXISTS TASK_LOCK (
        LOCK_KEY CHAR(36) NOT NULL,
        REGION VARCHAR(100) NOT NULL,
        CLIENT_ID CHAR(36),
        CREATED_DATE DATETIME NOT NULL,
        CONSTRAINT LOCK_PK PRIMARY KEY (LOCK_KEY, REGION)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;