spring:
  # Spring AI configuration
  ai:
    retry:
      max-attempts: 5
      backoff:
        initial-interval: 2s
        multiplier: 2
        max-interval: 30s
    vectorstore:
      opensearch:
        host: ${SPRING_AI_VECTORSTORE_OPENSEARCH_HOST:localhost}
        port: ${SPRING_AI_VECTORSTORE_OPENSEARCH_PORT:9200}
        scheme: ${SPRING_AI_VECTORSTORE_OPENSEARCH_SCHEME:http}
        username: ${SPRING_AI_VECTORSTORE_OPENSEARCH_USERNAME:}
        password: ${SPRING_AI_VECTORSTORE_OPENSEARCH_PASSWORD:}
        index-name: ${SPRING_AI_VECTORSTORE_OPENSEARCH_INDEX_NAME:vector_store}
        embedding-dimension: ${SPRING_AI_VECTORSTORE_OPENSEARCH_EMBEDDING_DIMENSION:1536}
    openai:
      api-key: ${SPRING_AI_OPENAI_API_KEY:${OPENAI_API_KEY:}}
      embedding:
        model: ${SPRING_AI_OPENAI_EMBEDDING_MODEL:text-embedding-3-small}
      chat:
        options:
          model: ${SPRING_AI_OPENAI_CHAT_OPTIONS_MODEL:gpt-4o-mini}
          stream-usage: true

# RAG configuration
rag:
  confluence:
    chunking:
      strategy: RECURSIVE_CHARACTER
      chunk-size: 512
      chunk-overlap: 50
      min-chunk-size-chars: 350
      min-chunk-length-to-embed: 5
      max-num-chunks: 10000
      keep-separators: true
      semantic-similarity-threshold: 0.5
      sentence-window-size: 3
  rrf:
    k: 60.0
    keyword-weight: 1.0
    title-weight: 2.0
    content-weight: 1.0
    date-boost-factor: 3.0
    path-boost-factor: 2.0
